# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-16 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorwho', '0003_auto_20190816_0656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Help',
            new_name='Feedback',
        ),
    ]
