# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-16 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorwho', '0004_auto_20190816_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complication',
            name='symptoms',
            field=models.CharField(max_length=200),
        ),
    ]
